//
//  BusListInteractor.swift
//  BookBus
//
//  Created by Thanos on 19/02/20.
//  Copyright (c) 2020 Thanos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BusListBusinessLogic
{
  func interactWithController(request: BusList.Something.Request)
    func updateBusDetails(details: BusDetailsData)
}

protocol BusListDataStore
{
    var busDetails: BusDetailsData? { get set }
    
  //var name: String { get set }
}

class BusListInteractor: BusListBusinessLogic, BusListDataStore
{
    var presenter: BusListPresentationLogic?
    var worker: BusListWorker?
    
    var busDetails: BusDetailsData?
    
  //var name: String = ""
  
  // MARK: Do something
  
  func interactWithController(request: BusList.Something.Request)
  {
    worker = BusListWorker()
    worker?.doSomeWork()
    
    let response = BusList.Something.Response()
    presenter?.presentData(response: response)
  }
    
    func updateBusDetails(details: BusDetailsData) {
        busDetails = details
    }
}
